### ISSUE TITLE
It OOMs at my 8Gb 2070s even with SD 1.5, this is ridiculous.

### ISSUE THREAD

**Issue by Seedmanc** [SUP3RMASS1VE/SD-Next#2]
Even with system fallback enabled. Only the lowest settings work, 512x512 at batch 1, going over that is impossible. No other software does this.

**Comment by SUP3RMASS1VE** [comment]
Yeah I gave up with sd-next, Too much hassle getting everything to work properly. If you use sd Forge there is an extension that makes it t look more like sd-next, can't remember what it's called though ui something. I'm using it on my sd Forge.

**Comment by Seedmanc** [comment]
I was hoping to use Next to run modern models like SD3, but if it can't handle even the oldest stuff, there's no future for it, sadly.

**Comment by SUP3RMASS1VE** [comment]
Have you checked out SwarmUI? That is so much better than sdnext

**Comment by Seedmanc** [comment]
I've heard of it, does it support CPU offloading for large models to save VRAM, like Forge does with Flux? I'm mainly interested in being able to run modern stuff like SD3 and Hunyan on my 8Gb card.
